//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClickOnce.NorthwindServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NorthwindServiceReference.INorthwindService")]
    public interface INorthwindService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INorthwindService/GetAllCategories", ReplyAction="http://tempuri.org/INorthwindService/GetAllCategoriesResponse")]
        WCF_Northwind.Contract.CategoryModel[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INorthwindService/GetAllCategories", ReplyAction="http://tempuri.org/INorthwindService/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<WCF_Northwind.Contract.CategoryModel[]> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INorthwindService/GetAllProducts", ReplyAction="http://tempuri.org/INorthwindService/GetAllProductsResponse")]
        WCF_Northwind.Contract.ProductModel[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INorthwindService/GetAllProducts", ReplyAction="http://tempuri.org/INorthwindService/GetAllProductsResponse")]
        System.Threading.Tasks.Task<WCF_Northwind.Contract.ProductModel[]> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INorthwindService/GetProductByCategoryID", ReplyAction="http://tempuri.org/INorthwindService/GetProductByCategoryIDResponse")]
        WCF_Northwind.Contract.ProductModel[] GetProductByCategoryID(int CategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INorthwindService/GetProductByCategoryID", ReplyAction="http://tempuri.org/INorthwindService/GetProductByCategoryIDResponse")]
        System.Threading.Tasks.Task<WCF_Northwind.Contract.ProductModel[]> GetProductByCategoryIDAsync(int CategoryID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INorthwindServiceChannel : WebClickOnce.NorthwindServiceReference.INorthwindService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NorthwindServiceClient : System.ServiceModel.ClientBase<WebClickOnce.NorthwindServiceReference.INorthwindService>, WebClickOnce.NorthwindServiceReference.INorthwindService {
        
        public NorthwindServiceClient() {
        }
        
        public NorthwindServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NorthwindServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NorthwindServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NorthwindServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_Northwind.Contract.CategoryModel[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<WCF_Northwind.Contract.CategoryModel[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public WCF_Northwind.Contract.ProductModel[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<WCF_Northwind.Contract.ProductModel[]> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public WCF_Northwind.Contract.ProductModel[] GetProductByCategoryID(int CategoryID) {
            return base.Channel.GetProductByCategoryID(CategoryID);
        }
        
        public System.Threading.Tasks.Task<WCF_Northwind.Contract.ProductModel[]> GetProductByCategoryIDAsync(int CategoryID) {
            return base.Channel.GetProductByCategoryIDAsync(CategoryID);
        }
    }
}
